export default [
    {
        id: 1,
        title: 'EL ENCANTO PLAZA LA MARINA-CONJUNTO HABITACIONAL',
        description: `PLAZA CON 30 LOCALES COMERCIALES DE 60 M2 Y 40 M2, CON ELEVADOR PANORAMICO, ESCALERAS Y UN ESPACIO DE ESTACIONAMIENTO. LA PLAZA COMERCIAL ESTA DISEÑADA CON UN ESTILO FUNCIONALISTA Y MODERNO, INTEGRANDO DETALLES EN HERRERIA, CON VENTANAS, PUERTAS Y BALCONES DE CRISTAL.
EL CONJUNTO HABITACIONAL CONSTA DE 2 BLOQUES DE DEPARTAMENTOS COMPUESTOS DE 3 NIVELES, DONDE C/U ESTA EQUIPADO CON UN ELEVADOR Y ESCALERAS DE EMERGENCIA. 
TORRE LOBOS CON 20 DEPARTAMENTOS DESDE LOS 70 M2 Y TORRE PAJAROS DE 14 DEPARTAMENTOS DESDE LOS 66 M2 DANDO UN TOTAL DE 34 DEPARTAMENTOS C/U CON BALCON.
INCLUYE UN AREA DE ALBERCA EN PLANTA BAJA Y ESTACIONAMIENTO, ASI COMO PORTERO VIRTUAL PARA ACCESAR, UN SISTEMA DE VIDEO VIGILANCIA E ILUMINACION LED. ESTRUCTURADO DE LOSA DE CONCRETO ARMADO, MUROS DE BLOCK Y ACABADOS EN YESO Y ESTUCO. 
DISEÑADO CON UN ESTILO MINIMALISTA Y MODERNO, INTEGRANDO DETALLES EN HERRERIA, VENTANAS DE CRISTAL Y ALUMINIO NEGRO.`,
        img: [''],
        shortDescription: 'PLAZA CON 30 LOCALES COMERCIALES DE 60 M2 Y 40 M2, CON ELEVADOR PANORAMICO, ESCALERAS Y UN ESPACIO DE ESTACIONAMIENTO...',
        direccion: 'AV. LA MARINA LOTE #10 S/N.',
        googleMaps: 'https://maps.app.goo.gl/YMGNyBXZVBwwEuk38'
    },
    {
        id: 2,
        title: 'EL ENCANTO CAMPO DE GOLF',
        description: `DESARROLLO DE 2 EDIFICIOS DE DEPARTAMENTOS SUBDIVIDIDOS EN 2 ETAPAS.
LA PRIMER ETAPA CONSTA DE 1 EDIFICIO DE 30 DEPARTAMENTOS, DISTRIBUIDO EN 5 NIVELES CON SERVICIO DE 2 ELEVADORES Y ESTACIONAMIENTO TECHADO CON 44 CAJONES DE ESTACIONAMIENTO.
EL EDIFICIO CUENTA CON AMPLIOS ESPACIOS DE AREA VERDE CON VISTAS AL CAMPO DE GOLF Y SUS ALREDEDORES, ALBERCA, ASADOR Y AREAS DE ESPARCIMIENTO.
EN LA SEGUNDA ETAPA SE INTEGRA UN ESPEJO DE LA PRIMERA, INTEGRANDO UNA TORRE DE 23 DEPARTAMENTOS, DISTRIBUIDOS EN 5 NIVELES CON SERVICIO DE 2 ELEVADORES Y ESTACIONAMIENTO TECHADO, DANDO ASI UN TOTAL DE 53 DEPARTAMENTOS Y 88 CAJONES DE ESTACIONAMIENTO POR LAS 2 ETAPAS.
ENCANTO LA MARINA CAMPO DE GOLF DESARROLLA UN ESTILO ARQUITECTONICO FUNCIONALISTA Y MODERNO, CON ACABADOS EN TENDENCIA QUE INTEGRAN AL EDIFICIO CON LA ZONA.
ESTRUCTURADO DE LOSA DE CONCRETO ARMADO, MUROS DE BLOCK Y ACABADOS EN YESO Y ESTUCO, ASI COMO DETALLES EN HERRERIA, VENTANAS CON MARCO DE ALUMINIO NEGRO, BARANDALES DE CRISTAL, PISO CERAMICO TIPO DUELA DE MADERA ANDINO NATURAL Y PISO DE PORCELANATO EN BAÑOS.`,
        img: [''],
        shortDescription: 'DESARROLLO DE 2 EDIFICIOS DE DEPARTAMENTOS SUBDIVIDIDOS EN 2 ETAPAS...',
        direccion: 'AV. DEL DELFIN, LOTE 12, FRACCIONAMIENTO LA MARINA, MAZATLÁN, SINALOA.',
        googleMaps: 'https://maps.app.goo.gl/KNSQKnhGiknjvsGX7'
    },
    {
        id: 3,
        title: 'EL ENCANTO CENTRAL PARK',
        description: `EDIFICIO DE DEPARTAMENTOS QUE CONSTA DE 6 NIVELES, 3 DEPARTAMENTOS EN DISTRIBUIDOS DE PRIMER A TERCER PISO CADA UNO DANDO UN TOTAL DE 12 DEPARTAMENTOS DE 3 TIPOS DESDE LOS 70 M2. CUENTA CON AMPLIO ESPACIO DE ROOF GARDEN CON ALBERCA, EQUIPAMIENTO DE GIMNASIO, ASADORES Y AREA SOCIAL, ASI COMO ESTACIONAMIENTO TECHADO EN PLANTA BAJA Y SERVICIO DE ELEVADOR.
DESARROLLA UN ESTILO ARQUITECTONICO FUNCIONALISTA Y MODERNO, CON ACABADOS EN TENDENCIA QUE INTEGRAN AL EDIFICIO CON EL ESPACIO.
ESTRUCTURADO DE LOSA DE CONCRETO ARMADO, MUROS DE BLOCK Y ACABADOS EN YESO Y ESTUCO EN EL QUE SE INTEGRAN DETALLES EN HERRERIA, CON VENTANAS DE ALUMINIO NEGRO Y PISO CERAMICO TIPO DUELA DE MADERA.
CUENTA CON ELEDOR PARA EL COMPLEJO.`,
        img: [''],
        shortDescription: 'EDIFICIO DE DEPARTAMENTOS QUE CONSTA DE 6 NIVELES, 3 DEPARTAMENTOS EN DISTRIBUIDOS DE PRIMER A TERCER PISO CADA UNO DANDO UN TOTAL DE 12 DEPARTAMENTOS DE 3 TIPOS DESDE LOS 70 M2. CUENTA CON AMPLIO ESPACIO DE ROOF GARDEN CON ALBERCA, EQUIPAMIENTO DE GIMNASIO, ASADORES Y AREA SOCIAL, ASI COMO ESTACIONAMIENTO TECHADO EN PLANTA BAJA Y SERVICIO DE ELEVADOR...',
        direccion: 'CALLE JUSTO SIERRA #17 LOS GIRASOLES',
        googleMaps: 'https://maps.app.goo.gl/UqRgH6z6sRCgZw146'
    },
    {
        id: 4,
        title: 'EL ENCANTO PERLA DEL PACIFICO',
        description: `EDIFICIO VERTICAL DE 26 NIVELES CON 126 DEPARTAMENTOS DE 6 TIPOS, QUE VAN DESDE LOS 53.4 M2 DEL TIPO LOFT HASTA AMPLIOS PENTHOUSE EN LOS ULTIMOS NIVELES.
EL COMPLEJO CUENTA CON 4 NIVELES DE ESTACIONAMIENTO, SIENDO EN TOTAL 134 CAJONES POR LOS 4 NIVELES Y ACCESO INDEPENDIENTE A RESTAURANTE, ASI COMO UN NIVEL DE AMENIDADES DONDE SE PODRA DISFRUTAR DE UNA ALBERCA INFINITY, AREA DE JUEGOS INFANTILES, BAR, SALON DE USOS MULTIPLES, SALA DE PROYECCION Y GIMNASIO. ADEMAS DE CONTAR CON LOBBY, VIDEO PORTERO, ACCESO CONTROLADO, 3 ELEVADORES DE 8P Y 1 ELEVADOR DE SERVICIO. 
DESARROLLA UN ESTILO ARQUITECTONICO FUNCIONALISTA Y MODERNO, CON ACABADOS EN TENDENCIA QUE INTEGRAN AL EDIFICIO CON LA ZONA TURISTICA.
ESTRUCTURADO DE LOSA DE CONCRETO ARMADO, MUROS DE BLOCK Y ACABADOS EN YESO Y ESTUCO, EN EL QUE SE INTEGRAN VENTANAS DE ALUMINIO NEGRO, BARANDALES DE CRISTAL Y PISO CERAMICO TIPO DUELA DE MADERA.`,
        img: [''],
        shortDescription: 'EDIFICIO VERTICAL DE 26 NIVELES CON 126 DEPARTAMENTOS DE 6 TIPOS, QUE VAN DESDE LOS 53.4 M2 DEL TIPO LOFT HASTA AMPLIOS PENTHOUSE EN LOS ULTIMOS NIVELES...',
        direccion: 'AV. DEL MAR 565, TELLERIA, 82017 MAZATLÁN, SINALOA',
        googleMaps: 'https://maps.app.goo.gl/LuTxeZ8ZeqbSrJ7r6'
    },
    {
        id: 5,
        title: 'EL ENCANTO PLAZA BUSINESS CENTER',
        description: `PLAZA DE USO COMERCIAL CONSTA DE 3 NIVELES DE LOCALES, DANDO UN TOTAL DE 90 LOCALES QUE VAN DESDE LOS 60 M2. CUENTA CON ESPACIO DE ESTACIONAMIENTO DE 151 CAJONES DISTRIBUIDOS EN PLANTA BAJA Y UN NIVEL EN SOTANO. ADEMAS DE ESTAR EQUIPADO CON 2 ELEVADORES PANORAMICOS Y 6 ESCALERAS ELECTRICAS.
LA PLAZA COMERCIAL ESTA DISEÑADA CON UN ESTILO FUNCIONALISTA Y MODERNO, INTEGRANDO DETALLES EN HERRERIA, CON VENTANAS, PUERTAS Y BARANDALES DE CRISTAL. ESTRUCTURADO DE LOSA DE CONCRETO ARMADO, MUROS DE BLOCK Y ACABADOS EN YESO Y ESTUCO`,
        img: [''],
        shortDescription: 'PLAZA DE USO COMERCIAL CONSTA DE 3 NIVELES DE LOCALES, DANDO UN TOTAL DE 90 LOCALES QUE VAN DESDE LOS 60 M2...',
        direccion: 'ESQUINA CON AV. LA MARINA Y PASEO EL ATLANTICO MANZANA 17 LOTE 2-CC2 / 2A-CC2',
        googleMaps: 'https://maps.app.goo.gl/t7F1Z2QcLGdPbMJ78'
    },
    {
        id: 6,
        title: 'EL ENCANTO OBSERVATORIO',
        description: `EDIFICIO DE DEPARTAMENTOS CON 7 NIVELES, 2 DEPARTAMENTOS POR NIVEL DANDO UN TOTAL DE 14 DEPARTAMENTOS. 
TERRAZAS PANORAMICAS Y VISTAS HACIA EL MAR`,
        img: [''],
        shortDescription: 'EDIFICIO DE DEPARTAMENTOS CON 7 NIVELES, 2 DEPARTAMENTOS POR NIVEL DANDO UN TOTAL DE 14 DEPARTAMENTOS...',
        direccion: 'CALLE CAMINO AL OBSERVATORIO, CERRO DEL VIGIA MAZATLAN, SINALOA.',
        googleMaps: 'https://maps.app.goo.gl/dTxvX3WRNBCSZnFK7'
    },
    {
        id: 7,
        title: 'EL ENCANTO TOREO',
        description: `PLAZA DE USO COMERCIAL QUE CONSTA DE #64 LOCALES DISTRIBUIDOS EN NIVEL PLANTA BAJA, NIVEL 1, NIVEL 2, Y NIVEL 3, ASÍ COMO UN ROOF GARDEN PARA LA TORRE DE DEPARTAMENTOS. EQUIPADA CON 2 ELEVADORES PANORÁMICOS Y 1 ESCALERAS DE SERVICIO 71 CAJONES DE ESTACIONAMIENTO Y TERRAZAS AMPLIAS DE USO COMÚN.
ASI COMO UNA TORRE DE 60 DEPARTAMENTOS QUE VAN DESDE LOS 60 M2 HASTA LOS 112.00 M2. PARA LOS DEPARTAMENTOS SE CUENTA CON MODULACIONES TIPO LOFT, 2 Y 3 RECAMARAS. ADEMAS DE 1 NIVEL DE AMENIDADES CON ALBERCA, AREA DE ASADORES, CAMASTROS, COCINA, BAÑOS GENERALES, ASI COMO AMPLIOS ESPACIOS AJARDINADOS. LA TORRE ESTA EQUIPADA CON 2 ELEVADORES EXCLUSIVOS PARA LA TORRE, ASI COMO LA LLEGADA DE LOS ELEVADES DE LA PLAZA COMERCIAL CON LLEGADA AL NIVEL DE ROOF GARDEN DESTINADA PARA ESPACIOS COMUNES DE ESTA MISMA TORRE, CUENTA CON 2 NIVELES DE ESTACIONAMIENTO CON UN TOTAL DE 79 CAJONES DE ESTACIONAMIENTO, CON LLEGADA AL 2 NIVEL POR MEDIO DE RAMPA O ELEVADOR PARA AUTOS, ADEMAS DE CONTAR CON VIDEO PORTERO Y ACCESO CONTROLADO.
EL ENCANTO TOREO ESTA DISEÑADO CON UN ESTILO FUNCIONALISTA Y MODERNO, INTEGRANDO DETALLES EN HERRERÍA, CON VENTANAS, PUERTAS Y BARANDALES DE CRISTAL. ESTRUCTURADO DE LOSACERO, MUROS DE BLOCK Y ACABADOS EN YESO Y ESTUCO.`,
        img: [''],
        shortDescription: 'PLAZA DE USO COMERCIAL QUE CONSTA DE #64 LOCALES DISTRIBUIDOS EN NIVEL PLANTA BAJA, NIVEL 1, NIVEL 2, Y NIVEL 3, ASÍ COMO UN ROOF GARDEN PARA LA TORRE DE DEPARTAMENTOS...',
        direccion: 'AV. RAFAEL BUELNA S/N FRACCIONAMIENTO LA ALAMEDA C.P. 82123',
        googleMaps: 'https://maps.app.goo.gl/NsU89JWbXapWUf4H8'
    },
    {
        id: 8,
        title: 'EL ENCANTO CLUB DE YATES',
        description: `EDIFICIO HABITACIONAL DE 5 NIVELES QUE CUENTA CON 65 UNIDADES DE DEPARTAMENTOS QUE VAN DESDE LOS 70.00 M2 HASTA LOS 184.00 M2, INTEGRANDO BALCONES, AMPLIAS TERRAZAS, ASI COMO VISTAS HACIA LOS MUELLES DE MARINA MAZATLÁN. PARA EL EQUIPAMIENTO SE CUENTA CON 4 ELEVADORES Y 1 DE SERVICIO, ASI COMO ESCALERAS CONVENCIONALES. CUENTA CON 1 NIVEL DE ESTACIONAMIENTO CON UN TOTAL DE 79 CAJONES.
EN EL PROYECTO SE INTEGRA 1 NIVEL DE ESPACIOS COMUNES COMO CLUB SOCIAL, GIMNASIO, AREA DE DESCANSO, AREA DE CAMASTROS, ASADORES Y UNA AMPLIA ALBERCA INFINITY, ADEMAS DE CONTAR CON VIDEO PORTERO Y ACCESO CONTROLADO.
EL ENCANTO CLUB DE YATES CUENTA CON UN ESTILO MODERNO Y FUNCIONALISTA, CON UN DISEÑO EXCLUSIVO E INNOVADOR PARA MAZATLÁN, INTEGRANDO DETALLES EN HERRERÍA, CON VENTANAS, PUERTAS Y BARANDALES DE CRISTAL. ESTRUCTURADO DE LOSACERO, MUROS DE BLOCK Y ACABADOS EN YESO Y ESTUCO.`,
        img: [''],
        shortDescription: 'EDIFICIO HABITACIONAL DE 5 NIVELES QUE CUENTA CON 65 UNIDADES DE DEPARTAMENTOS QUE VAN DESDE LOS 70.00 M2 HASTA LOS 184.00 M2, INTEGRANDO BALCONES, AMPLIAS TERRAZAS, ASI COMO VISTAS HACIA LOS MUELLES DE MARINA MAZATLÁN...',
        direccion: 'CALLE C. CORAL SUR / PRIVADA CORAL SUR, ISLA MARINA MAZATLÁN, MAZATLÁN SINALOA.',
        googleMaps: 'https://maps.app.goo.gl/3wEzmCP1ez9QzFsDA'
    },
    {
        id: 9,
        title: 'EL ENCANTO DE LAS LOMAS',
        description: `EDIFICIO HABITACIONAL DE 4 NIVELES QUE CUENTA CON 12 UNIDADES DE DEPARTAMENTOS, INTEGRANDO 4 DEPARTAMENTOS POR NIVEL. SE CUENTA CON MODULACIONES TIPO LOFT DE 52.00 M2 HABITACIONALES CON BALCONES DE 4.95 M2, ASI COMO MODULACIONES TIPO PLUS DE 80.00 M2 HABITACIONALES CON UN BALCON DE 6.60 M2, MISMOS QUE CUENTAN CON VISTAS HACIA LA CIUDAD. 
PARA EL EQUIPAMIENTO CUENTA CON 1 ELEVADOR ASI COMO ESCALERAS CONVENCIONALES. CUANTA CON 1 NIVEL DE ESTACIONAMIENTO CON UN TOTAL DE 12 CAJONES. ADEMAS DE CONTAR CON VIDEO PORTERO Y ACCESO CONTROLADO PARA LOS DEPARTAMENTOS. 
EN EL PROYECTO SE INTEGRA UN ROOF GARDEN CON ESPACIOS COMUNES COMO GIMNASIO, AREA DE DESCANSO, AREA DE CAMASTROS, ASADORES Y UNA AMPLIA ALBERCA. 
EL ENCANTO DE LAS LOMAS CUENTA CON UN ESTILO MODERNO Y FUNCIONALISTA, INTEGRANDO DETALLES EN HERRERÍA, CON VENTANAS, PUERTAS Y BARANDALES DE CRISTAL. ESTRUCTURADO DE LOSACERO, MUROS DE BLOCK Y ACABADOS EN YESO Y ESTUCO.`,
        img: [''],
        shortDescription: 'EDIFICIO HABITACIONAL DE 4 NIVELES QUE CUENTA CON 12 UNIDADES DE DEPARTAMENTOS, INTEGRANDO 4 DEPARTAMENTOS POR NIVEL...',
        direcion: 'CERRO DE CONEJOS #233, FRACCIONAMIENTO LOMAS DE MAZATLÁN C.P. 82110',
        googleMaps: 'https://maps.app.goo.gl/FNnMyHym5ormk8iK8'
    },
    {
        id: 10,
        title: 'EL ENCANTO RIO',
        description: `EDIFICIO HABITACIONAL DE 7 NIVELES QUE CUENTA CON 25 UNIDADES DE DEPARTAMENTOS. SE CUENTA CON 1 UNIDAD TIPO LOFT 1 DE 62.00 M2, 1 UNIDAD TIPO LOFT 2 DE 56.00 M2, ASI COMO 18 MODULACIONES TIPO A-B-AI DE 80.00 M2, ASI COMO 5 UNIDADES CON MODULACIONES TIPO BI DE 120.00 M2, MISMOS QUE CUENTAN CON VISTAS HACIA LA CIUDAD O HACIA EL ATRACTIVO ATARDECER.
PARA EL EQUIPAMIENTO CUENTA CON 1 ELEVADOR ASI COMO ESCALERAS CONVENCIONALES. CUANTA CON 1 NIVEL DE ESTACIONAMIENTO CON UN TOTAL DE 25 CAJONES. ADEMAS DE CONTAR CON VIDEO PORTERO Y ACCESO CONTROLADO PARA LOS DEPARTAMENTOS. 
EN EL PROYECTO SE INTEGRA UN ROOF GARDEN CON ESPACIOS COMUNES COMO GIMNASIO, AREA DE DESCANSO, AREA DE CAMASTROS, ASADORES Y UNA AMPLIA ALBERCA. 
EL ENCANTO RÍO CUENTA CON UN ESTILO MODERNO Y FUNCIONALISTA, INTEGRANDO DETALLES DE HERRERÍA Y VENTANAS DE CRISTAL. ESTRUCTURADO DE LOSACERO, MUROS DE BLOCK Y ACABADOS EN YESO Y ESTUCO.`,
        img: [''],
        shortDescription: 'EDIFICIO HABITACIONAL DE 7 NIVELES QUE CUENTA CON 25 UNIDADES DE DEPARTAMENTOS...',
        direccion: 'CALLE PAPAGAYO #208 MANZANA VII, COL. FERROCARRILERA, MAZATLÁN SINALOA',
        googleMaps: ''
    },
    {
        id: 11,
        title: 'ALTAMEDICA',
        description: `PLAZA DE USO COMERCIAL QUE CONSTA DE 23 LOCALES DISTRIBUIDOS EN NIVEL PLANTA BAJA CON LOCALES EN DOBLE ALTURA, NIVEL 1 Y NIVEL 2. 
        PARA EL EQUIPAMIENTO CUENTA CON 1 ELEVADOR PANORAMICO ASI COMO ESCALERAS CONVENCIONALES. CUENTA CON 1 NIVEL DE ESTACIONAMIENTO CON UN TOTAL DE 62 CAJONES, ADEMAS DE CONTAR CON ACCESO CONTROLADO.
        LA PLAZA COMERCIAL ESTA DISEÑADA CON UN ESTILO FUNCIONALISTA Y MODERNO, INTEGRANDO DETALLES EN HERRERIA, CON VENTANAS, PUERTAS Y BALCONES DE CRISTAL.`,
        img: [''],
        shortDescription: 'PLAZA DE USO COMERCIAL QUE CONSTA DE 23 LOCALES DISTRIBUIDOS EN NIVEL PLANTA BAJA CON LOCALES EN DOBLE ALTURA, NIVEL 1 Y NIVEL 2...',
        direccion: 'AV. PASEO DEL PACIFICO, MAZATLÁN SINALOA, SIN NUMERO.',
        googleMaps: ''
    }
]